{{- if .Values.credentials.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chp.fullname" . }}-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chp.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.credentials.ornnApiToken }}
  ORNN_API_TOKEN: {{ .Values.credentials.ornnApiToken | quote }}
  {{- end }}
  ORNN_API_BASE_URL: {{ .Values.ornn.baseUrl | quote }}
  ORNN_API_PRICE_PATH: {{ .Values.ornn.pricePath | quote }}
  {{- if .Values.credentials.prometheusUrl }}
  PROMETHEUS_URL: {{ .Values.credentials.prometheusUrl | quote }}
  {{- else if .Values.telemetry.prometheusUrl }}
  PROMETHEUS_URL: {{ .Values.telemetry.prometheusUrl | quote }}
  {{- end }}
  {{- if .Values.telemetry.query }}
  TELEMETRY_QUERY: {{ .Values.telemetry.query | quote }}
  {{- end }}
  {{- if .Values.credentials.marketApiUrl }}
  MARKET_API_URL: {{ .Values.credentials.marketApiUrl | quote }}
  {{- else if .Values.market.apiUrl }}
  MARKET_API_URL: {{ .Values.market.apiUrl | quote }}
  {{- end }}
  MARKET_API_PATH: {{ .Values.market.apiPath | quote }}
  MARKET_WRITE_ENABLED: {{ .Values.credentials.marketWriteEnabled | quote }}
  AUTH_SCHEME: {{ .Values.auth.scheme | quote }}
  AUTH_HEADER: {{ .Values.auth.header | quote }}
{{- end }}
